version: '3.8'

services:
  docker-registry-browser:
    build: .
    container_name: docker-registry-browser
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      # Registry configuration
      - REGISTRY_HOST=host.docker.internal:5000
      - REGISTRY_PROTOCOL=http
      # Optional: Basic auth if your registry requires it
      # - REGISTRY_USERNAME=username
      # - REGISTRY_PASSWORD=password
    extra_hosts:
      # For accessing host services (like local registry)
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Unraid template labels
      - "net.unraid.docker.managed=dockerman"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/docker/docs/main/assets/images/docker-icon.png"
    networks:
      - registry-network

networks:
  registry-network:
    driver: bridge
